// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileformat.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_fileformat_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_fileformat_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_fileformat_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_fileformat_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_fileformat_2eproto;
namespace OSMPBF {
class Blob;
struct BlobDefaultTypeInternal;
extern BlobDefaultTypeInternal _Blob_default_instance_;
class BlobHeader;
struct BlobHeaderDefaultTypeInternal;
extern BlobHeaderDefaultTypeInternal _BlobHeader_default_instance_;
}  // namespace OSMPBF
PROTOBUF_NAMESPACE_OPEN
template <>
::OSMPBF::Blob* Arena::CreateMaybeMessage<::OSMPBF::Blob>(Arena*);
template <>
::OSMPBF::BlobHeader* Arena::CreateMaybeMessage<::OSMPBF::BlobHeader>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace OSMPBF {

// ===================================================================


// -------------------------------------------------------------------

class Blob final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:OSMPBF.Blob) */ {
 public:
  inline Blob() : Blob(nullptr) {}
  ~Blob() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Blob(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Blob(const Blob& from);
  Blob(Blob&& from) noexcept
    : Blob() {
    *this = ::std::move(from);
  }

  inline Blob& operator=(const Blob& from) {
    CopyFrom(from);
    return *this;
  }
  inline Blob& operator=(Blob&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Blob& default_instance() {
    return *internal_default_instance();
  }
  enum DataCase {
    kRaw = 1,
    kZlibData = 3,
    kLzmaData = 4,
    kOBSOLETEBzip2Data = 5,
    kLz4Data = 6,
    kZstdData = 7,
    DATA_NOT_SET = 0,
  };

  static inline const Blob* internal_default_instance() {
    return reinterpret_cast<const Blob*>(
               &_Blob_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Blob& a, Blob& b) {
    a.Swap(&b);
  }
  inline void Swap(Blob* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Blob* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Blob* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Blob>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Blob& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Blob& from) {
    Blob::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Blob* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "OSMPBF.Blob";
  }
  protected:
  explicit Blob(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRawSizeFieldNumber = 2,
    kRawFieldNumber = 1,
    kZlibDataFieldNumber = 3,
    kLzmaDataFieldNumber = 4,
    kOBSOLETEBzip2DataFieldNumber = 5,
    kLz4DataFieldNumber = 6,
    kZstdDataFieldNumber = 7,
  };
  // optional int32 raw_size = 2;
  bool has_raw_size() const;
  void clear_raw_size() ;
  ::int32_t raw_size() const;
  void set_raw_size(::int32_t value);

  private:
  ::int32_t _internal_raw_size() const;
  void _internal_set_raw_size(::int32_t value);

  public:
  // bytes raw = 1;
  bool has_raw() const;
  void clear_raw() ;
  const std::string& raw() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_raw(Arg_&& arg, Args_... args);
  std::string* mutable_raw();
  PROTOBUF_NODISCARD std::string* release_raw();
  void set_allocated_raw(std::string* ptr);

  private:
  const std::string& _internal_raw() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_raw(
      const std::string& value);
  std::string* _internal_mutable_raw();

  public:
  // bytes zlib_data = 3;
  bool has_zlib_data() const;
  void clear_zlib_data() ;
  const std::string& zlib_data() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_zlib_data(Arg_&& arg, Args_... args);
  std::string* mutable_zlib_data();
  PROTOBUF_NODISCARD std::string* release_zlib_data();
  void set_allocated_zlib_data(std::string* ptr);

  private:
  const std::string& _internal_zlib_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_zlib_data(
      const std::string& value);
  std::string* _internal_mutable_zlib_data();

  public:
  // bytes lzma_data = 4;
  bool has_lzma_data() const;
  void clear_lzma_data() ;
  const std::string& lzma_data() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_lzma_data(Arg_&& arg, Args_... args);
  std::string* mutable_lzma_data();
  PROTOBUF_NODISCARD std::string* release_lzma_data();
  void set_allocated_lzma_data(std::string* ptr);

  private:
  const std::string& _internal_lzma_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_lzma_data(
      const std::string& value);
  std::string* _internal_mutable_lzma_data();

  public:
  // bytes OBSOLETE_bzip2_data = 5 [deprecated = true];
  [[deprecated]]  bool has_obsolete_bzip2_data() const;
  [[deprecated]]  void clear_obsolete_bzip2_data() ;
  [[deprecated]] const std::string& obsolete_bzip2_data() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  [[deprecated]] void set_obsolete_bzip2_data(Arg_&& arg, Args_... args);
  [[deprecated]] std::string* mutable_obsolete_bzip2_data();
  [[deprecated]] PROTOBUF_NODISCARD std::string* release_obsolete_bzip2_data();
  [[deprecated]] void set_allocated_obsolete_bzip2_data(std::string* ptr);

  private:
  const std::string& _internal_obsolete_bzip2_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_obsolete_bzip2_data(
      const std::string& value);
  std::string* _internal_mutable_obsolete_bzip2_data();

  public:
  // bytes lz4_data = 6;
  bool has_lz4_data() const;
  void clear_lz4_data() ;
  const std::string& lz4_data() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_lz4_data(Arg_&& arg, Args_... args);
  std::string* mutable_lz4_data();
  PROTOBUF_NODISCARD std::string* release_lz4_data();
  void set_allocated_lz4_data(std::string* ptr);

  private:
  const std::string& _internal_lz4_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_lz4_data(
      const std::string& value);
  std::string* _internal_mutable_lz4_data();

  public:
  // bytes zstd_data = 7;
  bool has_zstd_data() const;
  void clear_zstd_data() ;
  const std::string& zstd_data() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_zstd_data(Arg_&& arg, Args_... args);
  std::string* mutable_zstd_data();
  PROTOBUF_NODISCARD std::string* release_zstd_data();
  void set_allocated_zstd_data(std::string* ptr);

  private:
  const std::string& _internal_zstd_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_zstd_data(
      const std::string& value);
  std::string* _internal_mutable_zstd_data();

  public:
  void clear_data();
  DataCase data_case() const;
  // @@protoc_insertion_point(class_scope:OSMPBF.Blob)
 private:
  class _Internal;
  void set_has_raw();
  void set_has_zlib_data();
  void set_has_lzma_data();
  void set_has_obsolete_bzip2_data();
  void set_has_lz4_data();
  void set_has_zstd_data();

  inline bool has_data() const;
  inline void clear_has_data();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::int32_t raw_size_;
    union DataUnion {
      constexpr DataUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr raw_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr zlib_data_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lzma_data_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr obsolete_bzip2_data_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lz4_data_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr zstd_data_;
    } data_;
    ::uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_fileformat_2eproto;
};// -------------------------------------------------------------------

class BlobHeader final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:OSMPBF.BlobHeader) */ {
 public:
  inline BlobHeader() : BlobHeader(nullptr) {}
  ~BlobHeader() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR BlobHeader(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BlobHeader(const BlobHeader& from);
  BlobHeader(BlobHeader&& from) noexcept
    : BlobHeader() {
    *this = ::std::move(from);
  }

  inline BlobHeader& operator=(const BlobHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline BlobHeader& operator=(BlobHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BlobHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const BlobHeader* internal_default_instance() {
    return reinterpret_cast<const BlobHeader*>(
               &_BlobHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BlobHeader& a, BlobHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(BlobHeader* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BlobHeader* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BlobHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BlobHeader>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BlobHeader& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BlobHeader& from) {
    BlobHeader::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BlobHeader* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "OSMPBF.BlobHeader";
  }
  protected:
  explicit BlobHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kIndexdataFieldNumber = 2,
    kDatasizeFieldNumber = 3,
  };
  // required string type = 1;
  bool has_type() const;
  void clear_type() ;
  const std::string& type() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_type(Arg_&& arg, Args_... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* ptr);

  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(
      const std::string& value);
  std::string* _internal_mutable_type();

  public:
  // optional bytes indexdata = 2;
  bool has_indexdata() const;
  void clear_indexdata() ;
  const std::string& indexdata() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_indexdata(Arg_&& arg, Args_... args);
  std::string* mutable_indexdata();
  PROTOBUF_NODISCARD std::string* release_indexdata();
  void set_allocated_indexdata(std::string* ptr);

  private:
  const std::string& _internal_indexdata() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_indexdata(
      const std::string& value);
  std::string* _internal_mutable_indexdata();

  public:
  // required int32 datasize = 3;
  bool has_datasize() const;
  void clear_datasize() ;
  ::int32_t datasize() const;
  void set_datasize(::int32_t value);

  private:
  ::int32_t _internal_datasize() const;
  void _internal_set_datasize(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:OSMPBF.BlobHeader)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  ::size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr indexdata_;
    ::int32_t datasize_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_fileformat_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Blob

// optional int32 raw_size = 2;
inline bool Blob::has_raw_size() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Blob::clear_raw_size() {
  _impl_.raw_size_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t Blob::raw_size() const {
  // @@protoc_insertion_point(field_get:OSMPBF.Blob.raw_size)
  return _internal_raw_size();
}
inline void Blob::set_raw_size(::int32_t value) {
  _internal_set_raw_size(value);
  // @@protoc_insertion_point(field_set:OSMPBF.Blob.raw_size)
}
inline ::int32_t Blob::_internal_raw_size() const {
  return _impl_.raw_size_;
}
inline void Blob::_internal_set_raw_size(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.raw_size_ = value;
}

// bytes raw = 1;
inline bool Blob::has_raw() const {
  return data_case() == kRaw;
}
inline void Blob::set_has_raw() {
  _impl_._oneof_case_[0] = kRaw;
}
inline void Blob::clear_raw() {
  if (data_case() == kRaw) {
    _impl_.data_.raw_.Destroy();
    clear_has_data();
  }
}
inline const std::string& Blob::raw() const {
  // @@protoc_insertion_point(field_get:OSMPBF.Blob.raw)
  return _internal_raw();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Blob::set_raw(Arg_&& arg,
                                                     Args_... args) {
  if (data_case() != kRaw) {
    clear_data();

    set_has_raw();
    _impl_.data_.raw_.InitDefault();
  }
  _impl_.data_.raw_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:OSMPBF.Blob.raw)
}
inline std::string* Blob::mutable_raw() {
  std::string* _s = _internal_mutable_raw();
  // @@protoc_insertion_point(field_mutable:OSMPBF.Blob.raw)
  return _s;
}
inline const std::string& Blob::_internal_raw() const {
  if (data_case() != kRaw) {
    return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.data_.raw_.Get();
}
inline void Blob::_internal_set_raw(const std::string& value) {
  if (data_case() != kRaw) {
    clear_data();

    set_has_raw();
    _impl_.data_.raw_.InitDefault();
  }


  _impl_.data_.raw_.Set(value, GetArenaForAllocation());
}
inline std::string* Blob::_internal_mutable_raw() {
  if (data_case() != kRaw) {
    clear_data();

    set_has_raw();
    _impl_.data_.raw_.InitDefault();
  }
  return _impl_.data_.raw_.Mutable( GetArenaForAllocation());
}
inline std::string* Blob::release_raw() {
  // @@protoc_insertion_point(field_release:OSMPBF.Blob.raw)
  if (data_case() != kRaw) {
    return nullptr;
  }
  clear_has_data();
  return _impl_.data_.raw_.Release();
}
inline void Blob::set_allocated_raw(std::string* value) {
  if (has_data()) {
    clear_data();
  }
  if (value != nullptr) {
    set_has_raw();
    _impl_.data_.raw_.InitAllocated(value, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:OSMPBF.Blob.raw)
}

// bytes zlib_data = 3;
inline bool Blob::has_zlib_data() const {
  return data_case() == kZlibData;
}
inline void Blob::set_has_zlib_data() {
  _impl_._oneof_case_[0] = kZlibData;
}
inline void Blob::clear_zlib_data() {
  if (data_case() == kZlibData) {
    _impl_.data_.zlib_data_.Destroy();
    clear_has_data();
  }
}
inline const std::string& Blob::zlib_data() const {
  // @@protoc_insertion_point(field_get:OSMPBF.Blob.zlib_data)
  return _internal_zlib_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Blob::set_zlib_data(Arg_&& arg,
                                                     Args_... args) {
  if (data_case() != kZlibData) {
    clear_data();

    set_has_zlib_data();
    _impl_.data_.zlib_data_.InitDefault();
  }
  _impl_.data_.zlib_data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:OSMPBF.Blob.zlib_data)
}
inline std::string* Blob::mutable_zlib_data() {
  std::string* _s = _internal_mutable_zlib_data();
  // @@protoc_insertion_point(field_mutable:OSMPBF.Blob.zlib_data)
  return _s;
}
inline const std::string& Blob::_internal_zlib_data() const {
  if (data_case() != kZlibData) {
    return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.data_.zlib_data_.Get();
}
inline void Blob::_internal_set_zlib_data(const std::string& value) {
  if (data_case() != kZlibData) {
    clear_data();

    set_has_zlib_data();
    _impl_.data_.zlib_data_.InitDefault();
  }


  _impl_.data_.zlib_data_.Set(value, GetArenaForAllocation());
}
inline std::string* Blob::_internal_mutable_zlib_data() {
  if (data_case() != kZlibData) {
    clear_data();

    set_has_zlib_data();
    _impl_.data_.zlib_data_.InitDefault();
  }
  return _impl_.data_.zlib_data_.Mutable( GetArenaForAllocation());
}
inline std::string* Blob::release_zlib_data() {
  // @@protoc_insertion_point(field_release:OSMPBF.Blob.zlib_data)
  if (data_case() != kZlibData) {
    return nullptr;
  }
  clear_has_data();
  return _impl_.data_.zlib_data_.Release();
}
inline void Blob::set_allocated_zlib_data(std::string* value) {
  if (has_data()) {
    clear_data();
  }
  if (value != nullptr) {
    set_has_zlib_data();
    _impl_.data_.zlib_data_.InitAllocated(value, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:OSMPBF.Blob.zlib_data)
}

// bytes lzma_data = 4;
inline bool Blob::has_lzma_data() const {
  return data_case() == kLzmaData;
}
inline void Blob::set_has_lzma_data() {
  _impl_._oneof_case_[0] = kLzmaData;
}
inline void Blob::clear_lzma_data() {
  if (data_case() == kLzmaData) {
    _impl_.data_.lzma_data_.Destroy();
    clear_has_data();
  }
}
inline const std::string& Blob::lzma_data() const {
  // @@protoc_insertion_point(field_get:OSMPBF.Blob.lzma_data)
  return _internal_lzma_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Blob::set_lzma_data(Arg_&& arg,
                                                     Args_... args) {
  if (data_case() != kLzmaData) {
    clear_data();

    set_has_lzma_data();
    _impl_.data_.lzma_data_.InitDefault();
  }
  _impl_.data_.lzma_data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:OSMPBF.Blob.lzma_data)
}
inline std::string* Blob::mutable_lzma_data() {
  std::string* _s = _internal_mutable_lzma_data();
  // @@protoc_insertion_point(field_mutable:OSMPBF.Blob.lzma_data)
  return _s;
}
inline const std::string& Blob::_internal_lzma_data() const {
  if (data_case() != kLzmaData) {
    return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.data_.lzma_data_.Get();
}
inline void Blob::_internal_set_lzma_data(const std::string& value) {
  if (data_case() != kLzmaData) {
    clear_data();

    set_has_lzma_data();
    _impl_.data_.lzma_data_.InitDefault();
  }


  _impl_.data_.lzma_data_.Set(value, GetArenaForAllocation());
}
inline std::string* Blob::_internal_mutable_lzma_data() {
  if (data_case() != kLzmaData) {
    clear_data();

    set_has_lzma_data();
    _impl_.data_.lzma_data_.InitDefault();
  }
  return _impl_.data_.lzma_data_.Mutable( GetArenaForAllocation());
}
inline std::string* Blob::release_lzma_data() {
  // @@protoc_insertion_point(field_release:OSMPBF.Blob.lzma_data)
  if (data_case() != kLzmaData) {
    return nullptr;
  }
  clear_has_data();
  return _impl_.data_.lzma_data_.Release();
}
inline void Blob::set_allocated_lzma_data(std::string* value) {
  if (has_data()) {
    clear_data();
  }
  if (value != nullptr) {
    set_has_lzma_data();
    _impl_.data_.lzma_data_.InitAllocated(value, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:OSMPBF.Blob.lzma_data)
}

// bytes OBSOLETE_bzip2_data = 5 [deprecated = true];
inline bool Blob::has_obsolete_bzip2_data() const {
  return data_case() == kOBSOLETEBzip2Data;
}
inline void Blob::set_has_obsolete_bzip2_data() {
  _impl_._oneof_case_[0] = kOBSOLETEBzip2Data;
}
inline void Blob::clear_obsolete_bzip2_data() {
  if (data_case() == kOBSOLETEBzip2Data) {
    _impl_.data_.obsolete_bzip2_data_.Destroy();
    clear_has_data();
  }
}
inline const std::string& Blob::obsolete_bzip2_data() const {
  // @@protoc_insertion_point(field_get:OSMPBF.Blob.OBSOLETE_bzip2_data)
  return _internal_obsolete_bzip2_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Blob::set_obsolete_bzip2_data(Arg_&& arg,
                                                     Args_... args) {
  if (data_case() != kOBSOLETEBzip2Data) {
    clear_data();

    set_has_obsolete_bzip2_data();
    _impl_.data_.obsolete_bzip2_data_.InitDefault();
  }
  _impl_.data_.obsolete_bzip2_data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:OSMPBF.Blob.OBSOLETE_bzip2_data)
}
inline std::string* Blob::mutable_obsolete_bzip2_data() {
  std::string* _s = _internal_mutable_obsolete_bzip2_data();
  // @@protoc_insertion_point(field_mutable:OSMPBF.Blob.OBSOLETE_bzip2_data)
  return _s;
}
inline const std::string& Blob::_internal_obsolete_bzip2_data() const {
  if (data_case() != kOBSOLETEBzip2Data) {
    return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.data_.obsolete_bzip2_data_.Get();
}
inline void Blob::_internal_set_obsolete_bzip2_data(const std::string& value) {
  if (data_case() != kOBSOLETEBzip2Data) {
    clear_data();

    set_has_obsolete_bzip2_data();
    _impl_.data_.obsolete_bzip2_data_.InitDefault();
  }


  _impl_.data_.obsolete_bzip2_data_.Set(value, GetArenaForAllocation());
}
inline std::string* Blob::_internal_mutable_obsolete_bzip2_data() {
  if (data_case() != kOBSOLETEBzip2Data) {
    clear_data();

    set_has_obsolete_bzip2_data();
    _impl_.data_.obsolete_bzip2_data_.InitDefault();
  }
  return _impl_.data_.obsolete_bzip2_data_.Mutable( GetArenaForAllocation());
}
inline std::string* Blob::release_obsolete_bzip2_data() {
  // @@protoc_insertion_point(field_release:OSMPBF.Blob.OBSOLETE_bzip2_data)
  if (data_case() != kOBSOLETEBzip2Data) {
    return nullptr;
  }
  clear_has_data();
  return _impl_.data_.obsolete_bzip2_data_.Release();
}
inline void Blob::set_allocated_obsolete_bzip2_data(std::string* value) {
  if (has_data()) {
    clear_data();
  }
  if (value != nullptr) {
    set_has_obsolete_bzip2_data();
    _impl_.data_.obsolete_bzip2_data_.InitAllocated(value, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:OSMPBF.Blob.OBSOLETE_bzip2_data)
}

// bytes lz4_data = 6;
inline bool Blob::has_lz4_data() const {
  return data_case() == kLz4Data;
}
inline void Blob::set_has_lz4_data() {
  _impl_._oneof_case_[0] = kLz4Data;
}
inline void Blob::clear_lz4_data() {
  if (data_case() == kLz4Data) {
    _impl_.data_.lz4_data_.Destroy();
    clear_has_data();
  }
}
inline const std::string& Blob::lz4_data() const {
  // @@protoc_insertion_point(field_get:OSMPBF.Blob.lz4_data)
  return _internal_lz4_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Blob::set_lz4_data(Arg_&& arg,
                                                     Args_... args) {
  if (data_case() != kLz4Data) {
    clear_data();

    set_has_lz4_data();
    _impl_.data_.lz4_data_.InitDefault();
  }
  _impl_.data_.lz4_data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:OSMPBF.Blob.lz4_data)
}
inline std::string* Blob::mutable_lz4_data() {
  std::string* _s = _internal_mutable_lz4_data();
  // @@protoc_insertion_point(field_mutable:OSMPBF.Blob.lz4_data)
  return _s;
}
inline const std::string& Blob::_internal_lz4_data() const {
  if (data_case() != kLz4Data) {
    return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.data_.lz4_data_.Get();
}
inline void Blob::_internal_set_lz4_data(const std::string& value) {
  if (data_case() != kLz4Data) {
    clear_data();

    set_has_lz4_data();
    _impl_.data_.lz4_data_.InitDefault();
  }


  _impl_.data_.lz4_data_.Set(value, GetArenaForAllocation());
}
inline std::string* Blob::_internal_mutable_lz4_data() {
  if (data_case() != kLz4Data) {
    clear_data();

    set_has_lz4_data();
    _impl_.data_.lz4_data_.InitDefault();
  }
  return _impl_.data_.lz4_data_.Mutable( GetArenaForAllocation());
}
inline std::string* Blob::release_lz4_data() {
  // @@protoc_insertion_point(field_release:OSMPBF.Blob.lz4_data)
  if (data_case() != kLz4Data) {
    return nullptr;
  }
  clear_has_data();
  return _impl_.data_.lz4_data_.Release();
}
inline void Blob::set_allocated_lz4_data(std::string* value) {
  if (has_data()) {
    clear_data();
  }
  if (value != nullptr) {
    set_has_lz4_data();
    _impl_.data_.lz4_data_.InitAllocated(value, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:OSMPBF.Blob.lz4_data)
}

// bytes zstd_data = 7;
inline bool Blob::has_zstd_data() const {
  return data_case() == kZstdData;
}
inline void Blob::set_has_zstd_data() {
  _impl_._oneof_case_[0] = kZstdData;
}
inline void Blob::clear_zstd_data() {
  if (data_case() == kZstdData) {
    _impl_.data_.zstd_data_.Destroy();
    clear_has_data();
  }
}
inline const std::string& Blob::zstd_data() const {
  // @@protoc_insertion_point(field_get:OSMPBF.Blob.zstd_data)
  return _internal_zstd_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Blob::set_zstd_data(Arg_&& arg,
                                                     Args_... args) {
  if (data_case() != kZstdData) {
    clear_data();

    set_has_zstd_data();
    _impl_.data_.zstd_data_.InitDefault();
  }
  _impl_.data_.zstd_data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:OSMPBF.Blob.zstd_data)
}
inline std::string* Blob::mutable_zstd_data() {
  std::string* _s = _internal_mutable_zstd_data();
  // @@protoc_insertion_point(field_mutable:OSMPBF.Blob.zstd_data)
  return _s;
}
inline const std::string& Blob::_internal_zstd_data() const {
  if (data_case() != kZstdData) {
    return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.data_.zstd_data_.Get();
}
inline void Blob::_internal_set_zstd_data(const std::string& value) {
  if (data_case() != kZstdData) {
    clear_data();

    set_has_zstd_data();
    _impl_.data_.zstd_data_.InitDefault();
  }


  _impl_.data_.zstd_data_.Set(value, GetArenaForAllocation());
}
inline std::string* Blob::_internal_mutable_zstd_data() {
  if (data_case() != kZstdData) {
    clear_data();

    set_has_zstd_data();
    _impl_.data_.zstd_data_.InitDefault();
  }
  return _impl_.data_.zstd_data_.Mutable( GetArenaForAllocation());
}
inline std::string* Blob::release_zstd_data() {
  // @@protoc_insertion_point(field_release:OSMPBF.Blob.zstd_data)
  if (data_case() != kZstdData) {
    return nullptr;
  }
  clear_has_data();
  return _impl_.data_.zstd_data_.Release();
}
inline void Blob::set_allocated_zstd_data(std::string* value) {
  if (has_data()) {
    clear_data();
  }
  if (value != nullptr) {
    set_has_zstd_data();
    _impl_.data_.zstd_data_.InitAllocated(value, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:OSMPBF.Blob.zstd_data)
}

inline bool Blob::has_data() const {
  return data_case() != DATA_NOT_SET;
}
inline void Blob::clear_has_data() {
  _impl_._oneof_case_[0] = DATA_NOT_SET;
}
inline Blob::DataCase Blob::data_case() const {
  return Blob::DataCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// BlobHeader

// required string type = 1;
inline bool BlobHeader::has_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void BlobHeader::clear_type() {
  _impl_.type_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& BlobHeader::type() const {
  // @@protoc_insertion_point(field_get:OSMPBF.BlobHeader.type)
  return _internal_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void BlobHeader::set_type(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.type_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:OSMPBF.BlobHeader.type)
}
inline std::string* BlobHeader::mutable_type() {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:OSMPBF.BlobHeader.type)
  return _s;
}
inline const std::string& BlobHeader::_internal_type() const {
  return _impl_.type_.Get();
}
inline void BlobHeader::_internal_set_type(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;


  _impl_.type_.Set(value, GetArenaForAllocation());
}
inline std::string* BlobHeader::_internal_mutable_type() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.type_.Mutable( GetArenaForAllocation());
}
inline std::string* BlobHeader::release_type() {
  // @@protoc_insertion_point(field_release:OSMPBF.BlobHeader.type)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.type_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void BlobHeader::set_allocated_type(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.type_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.type_.IsDefault()) {
          _impl_.type_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:OSMPBF.BlobHeader.type)
}

// optional bytes indexdata = 2;
inline bool BlobHeader::has_indexdata() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void BlobHeader::clear_indexdata() {
  _impl_.indexdata_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& BlobHeader::indexdata() const {
  // @@protoc_insertion_point(field_get:OSMPBF.BlobHeader.indexdata)
  return _internal_indexdata();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void BlobHeader::set_indexdata(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.indexdata_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:OSMPBF.BlobHeader.indexdata)
}
inline std::string* BlobHeader::mutable_indexdata() {
  std::string* _s = _internal_mutable_indexdata();
  // @@protoc_insertion_point(field_mutable:OSMPBF.BlobHeader.indexdata)
  return _s;
}
inline const std::string& BlobHeader::_internal_indexdata() const {
  return _impl_.indexdata_.Get();
}
inline void BlobHeader::_internal_set_indexdata(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;


  _impl_.indexdata_.Set(value, GetArenaForAllocation());
}
inline std::string* BlobHeader::_internal_mutable_indexdata() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.indexdata_.Mutable( GetArenaForAllocation());
}
inline std::string* BlobHeader::release_indexdata() {
  // @@protoc_insertion_point(field_release:OSMPBF.BlobHeader.indexdata)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.indexdata_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.indexdata_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void BlobHeader::set_allocated_indexdata(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.indexdata_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.indexdata_.IsDefault()) {
          _impl_.indexdata_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:OSMPBF.BlobHeader.indexdata)
}

// required int32 datasize = 3;
inline bool BlobHeader::has_datasize() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void BlobHeader::clear_datasize() {
  _impl_.datasize_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t BlobHeader::datasize() const {
  // @@protoc_insertion_point(field_get:OSMPBF.BlobHeader.datasize)
  return _internal_datasize();
}
inline void BlobHeader::set_datasize(::int32_t value) {
  _internal_set_datasize(value);
  // @@protoc_insertion_point(field_set:OSMPBF.BlobHeader.datasize)
}
inline ::int32_t BlobHeader::_internal_datasize() const {
  return _impl_.datasize_;
}
inline void BlobHeader::_internal_set_datasize(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.datasize_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace OSMPBF


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_fileformat_2eproto_2epb_2eh
